# Generated by Django 6.0 on 2025-12-09 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_portfolio_content_portfolio_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='site_url',
            field=models.URLField(blank=True),
        ),
    ]
