# Generated by Django 6.0 on 2025-12-09 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_portfolio_site_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='facebook',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='github',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='linkdln',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='telegram',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='twitter',
        ),
    ]
