# Generated by Django 6.0 on 2025-12-09 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_portfolio_facebook_remove_portfolio_github_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='budget',
            new_name='phone',
        ),
    ]
